GET http://localhost:8080/formations
Content-Type: application/json

###
GET http://localhost:8080/formations/angular
Content-Type: application/json

###
GET http://localhost:8080/formations/be1ee3a0-898b-433b-ae1f-b3f2ce97bc54
Content-Type: application/json

###
POST http://localhost:8080/formations
Content-Type: application/json

{
  "id": "61ece15d-136b-4e68-842f-0a5c68e8845e",
  "title": "Spring Data",
  "description": "Spring Data description",
  "location": "EPHEC",
  "date": "2025-11-15",
  "tags": [
    {
      "id": "bc843212-c5c1-4da2-a861-29d1e6ce22d8",
      "text": "Java"
    },
    {
      "id": "fa78f5fa-5951-49c8-ae3b-83acc7ba8107",
      "text": "SpringBoot"
    }
  ]
}

###
DELETE http://localhost:8080/formations/61ece15d-136b-4e68-842f-0a5c68e8845e